"""Command Guardrails — validate AI-generated commands before execution.

Defends against:
- Indirect Prompt Injection: malicious instructions embedded in BookStack, device names, etc.
- Accidental destructive commands generated by hallucination.
- Direct injection attacks via natural language input.

Two severity levels:
  BLOCK   — command is forbidden; operation must not proceed.
  WARN    — command is suspicious; flagged in the response but allowed.

Usage:
    violations = check_ssh_commands(["reload", "sh run"])
    violations = check_action_plan(action_plan_dict, intent)
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class Severity(str, Enum):
    BLOCK = "block"
    WARN  = "warn"


@dataclass
class GuardrailViolation:
    severity: Severity
    rule: str
    command: str
    message: str


@dataclass
class GuardrailResult:
    violations: list[GuardrailViolation] = field(default_factory=list)

    @property
    def blocked(self) -> bool:
        return any(v.severity == Severity.BLOCK for v in self.violations)

    @property
    def block_reason(self) -> str | None:
        for v in self.violations:
            if v.severity == Severity.BLOCK:
                return v.message
        return None

    @property
    def warnings(self) -> list[str]:
        return [v.message for v in self.violations if v.severity == Severity.WARN]


# ── SSH Command Rules ─────────────────────────────────────────────────────────

_SSH_BLOCK_RULES: list[tuple[str, re.Pattern[str], str]] = [
    (
        "device_reload",
        re.compile(r"^\s*reload\s*$", re.IGNORECASE),
        "Comando 'reload' bloqueia acesso ao dispositivo — operação cancelada.",
    ),
    (
        "erase_config",
        re.compile(r"\berase\s+(startup-config|nvram:|flash:)", re.IGNORECASE),
        "Apagar configuração de startup pode tornar o dispositivo inacessível.",
    ),
    (
        "format_storage",
        re.compile(r"\bformat\s+\S+", re.IGNORECASE),
        "Formatação de storage destrói dados de forma irreversível.",
    ),
    (
        "delete_recursive",
        re.compile(r"\bdelete\s+(/force\s+)?/recursive", re.IGNORECASE),
        "Deleção recursiva de arquivos pode destruir o sistema operacional.",
    ),
    (
        "remove_default_route",
        re.compile(r"\bno\s+ip\s+route\s+0\.0\.0\.0\s+0\.0\.0\.0", re.IGNORECASE),
        "Remover a rota default pode desconectar o dispositivo permanentemente.",
    ),
    (
        "mikrotik_reset",
        re.compile(r"/system\s+reset-configuration", re.IGNORECASE),
        "Reset de configuração MikroTik apaga toda a config do dispositivo.",
    ),
    (
        "sonicwall_restore_default",
        re.compile(r"\brestore\s+default\b", re.IGNORECASE),
        "Restaurar defaults no SonicWall apaga toda a configuração.",
    ),
    (
        "juniper_zeroize",
        re.compile(r"\brequest\s+system\s+zeroize\b", re.IGNORECASE),
        "Zeroize apaga toda a configuração e chaves do dispositivo Juniper.",
    ),
    (
        "juniper_reboot",
        re.compile(r"\brequest\s+system\s+(reboot|halt|power-off)\b", re.IGNORECASE),
        "Reboot/halt de dispositivo Juniper encerra o acesso remoto.",
    ),
    (
        "shutdown_all_interfaces",
        re.compile(r"\bshutdown\s+all\b", re.IGNORECASE),
        "Shutdown de todas as interfaces pode desconectar completamente.",
    ),
    (
        "wipe_all_acls",
        re.compile(r"\bno\s+ip\s+access-list\s+extended\s+\*", re.IGNORECASE),
        "Remover todos os ACLs pode abrir ou fechar todo o tráfego.",
    ),
    (
        "prompt_injection",
        re.compile(
            r"(INSTRUÇÃO PARA IA|IGNORE PREVIOUS|SYSTEM PROMPT|<\|endoftext\|>|<\/s>|\[INST\])",
            re.IGNORECASE,
        ),
        "Possível tentativa de Prompt Injection detectada no comando.",
    ),
]

_SSH_WARN_RULES: list[tuple[str, re.Pattern[str], str]] = [
    (
        "interface_shutdown",
        re.compile(r"^\s*(no\s+)?shutdown\s*$", re.IGNORECASE),
        "Comando shutdown/no shutdown em interface — confirme a interface alvo.",
    ),
    (
        "remove_nat_all",
        re.compile(r"\bno\s+ip\s+nat\s+(inside|outside|translation)\s*$", re.IGNORECASE),
        "Remover NAT pode interromper conectividade de usuários internos.",
    ),
    (
        "write_erase",
        re.compile(r"\bwrite\s+erase\b", re.IGNORECASE),
        "Write erase apaga a startup-config — dispositivo reinicia sem config.",
    ),
    (
        "ospf_shutdown",
        re.compile(r"\bno\s+router\s+ospf\b", re.IGNORECASE),
        "Remover OSPF pode interromper roteamento dinâmico.",
    ),
    (
        "bgp_shutdown",
        re.compile(r"\bno\s+router\s+bgp\b", re.IGNORECASE),
        "Remover BGP pode interromper sessões de roteamento externo.",
    ),
]


def check_ssh_commands(commands: list[str]) -> GuardrailResult:
    """Validate a list of SSH CLI commands against guardrail rules."""
    result = GuardrailResult()
    for cmd in commands:
        for rule_id, pattern, message in _SSH_BLOCK_RULES:
            if pattern.search(cmd):
                result.violations.append(
                    GuardrailViolation(Severity.BLOCK, rule_id, cmd, message)
                )
        for rule_id, pattern, message in _SSH_WARN_RULES:
            if pattern.search(cmd):
                result.violations.append(
                    GuardrailViolation(Severity.WARN, rule_id, cmd, message)
                )
    return result


# ── Action Plan Rules ─────────────────────────────────────────────────────────

_DANGEROUS_INTENTS = {
    "delete_rule",
    "delete_nat_policy",
    "delete_route_policy",
    "delete_vlan",
    "direct_ssh",
}

_PROMPT_INJECTION_RE = re.compile(
    r"(INSTRUÇÃO PARA IA|IGNORE PREVIOUS|SYSTEM PROMPT|<\|endoftext\|>|<\/s>|\[INST\]"
    r"|ignore all previous|disregard (the|all) (above|previous)|act as)",
    re.IGNORECASE,
)


def check_action_plan(action_plan: dict[str, Any], user_input: str = "") -> GuardrailResult:
    """Validate a structured action plan dict against guardrail rules."""
    result = GuardrailResult()
    intent = action_plan.get("intent", "")

    # Prompt injection in user input
    if _PROMPT_INJECTION_RE.search(user_input):
        result.violations.append(GuardrailViolation(
            Severity.BLOCK, "prompt_injection_input", user_input[:120],
            "Possível Prompt Injection detectado no input do usuário.",
        ))

    # Prompt injection in any string field of action_plan
    plan_str = str(action_plan)
    if _PROMPT_INJECTION_RE.search(plan_str):
        result.violations.append(GuardrailViolation(
            Severity.BLOCK, "prompt_injection_plan", plan_str[:120],
            "Possível Prompt Injection detectado no plano de ação gerado.",
        ))

    # Validate SSH commands embedded in plan
    ssh_commands = action_plan.get("ssh_commands") or []
    if ssh_commands:
        ssh_result = check_ssh_commands(ssh_commands)
        result.violations.extend(ssh_result.violations)

    # Warn for dangerous intents with no confirmation context
    if intent in _DANGEROUS_INTENTS:
        result.violations.append(GuardrailViolation(
            Severity.WARN, "destructive_intent", intent,
            f"Intent '{intent}' é destrutivo — confirme que o plano de ação está correto.",
        ))

    return result
